//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMVS_WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountyNumber
    {
        public int CountyID { get; set; }
        public string CountyName { get; set; }
        public int mapNumber { get; set; }
        public int alphaOrder { get; set; }
        public string Status { get; set; }
    }
}
