//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMVS_WindowsFormsApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CountiesEntities : DbContext
    {
        public CountiesEntities()
            : base("name=CountiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdjacentCounties> AdjacentCounties1 { get; set; }
        public virtual DbSet<CountyNumber> CountyNumbers { get; set; }   
    
        public virtual ObjectResult<isAdjacent_Result> isAdjacent(Nullable<int> county1, Nullable<int> county2)
        {
            var county1Parameter = county1.HasValue ?
                new ObjectParameter("County1", county1) :
                new ObjectParameter("County1", typeof(int));
    
            var county2Parameter = county2.HasValue ?
                new ObjectParameter("County2", county2) :
                new ObjectParameter("County2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isAdjacent_Result>("isAdjacent", county1Parameter, county2Parameter);
        }
    }
}
